/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/LogoutModal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/DeleteModal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/SkeletonLoader`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ErrorState`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/LoadingState`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useExpenses`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create-expense` | `/create-expense`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step-1`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step-2`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step-3`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/expense/[id]` | `/expense/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/LogoutModal`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/DeleteModal`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/SkeletonLoader`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/ErrorState`; params?: Router.UnknownOutputParams; } | { pathname: `/../components/ui/LoadingState`; params?: Router.UnknownOutputParams; } | { pathname: `/../hooks/useExpenses`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/create-expense` | `/create-expense`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/step-1`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/step-2`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/step-3`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/expense/[id]` | `/expense/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/dashboard${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/../components/ui/LogoutModal${`?${string}` | `#${string}` | ''}` | `/../components/ui/DeleteModal${`?${string}` | `#${string}` | ''}` | `/../components/ui/SkeletonLoader${`?${string}` | `#${string}` | ''}` | `/../components/ui/ErrorState${`?${string}` | `#${string}` | ''}` | `/../components/ui/LoadingState${`?${string}` | `#${string}` | ''}` | `/../hooks/useExpenses${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/create-expense${`?${string}` | `#${string}` | ''}` | `/create-expense${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/onboarding${`?${string}` | `#${string}` | ''}` | `/onboarding/step-1${`?${string}` | `#${string}` | ''}` | `/onboarding/step-2${`?${string}` | `#${string}` | ''}` | `/onboarding/step-3${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/LogoutModal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/DeleteModal`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/SkeletonLoader`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/ErrorState`; params?: Router.UnknownInputParams; } | { pathname: `/../components/ui/LoadingState`; params?: Router.UnknownInputParams; } | { pathname: `/../hooks/useExpenses`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create-expense` | `/create-expense`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step-1`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step-2`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/step-3`; params?: Router.UnknownInputParams; } | `${'/(tabs)'}/expense/${Router.SingleRoutePart<T>}` | `/expense/${Router.SingleRoutePart<T>}` | { pathname: `${'/(tabs)'}/expense/[id]` | `/expense/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
